#! /usr/bin/python

#main running script

import sys

sys.path.append("aws_pipeline/pipeline")
sys.path.append("pipeline")

import pipeline
import pipeline.pipeline

pipeline.pipeline.start(sys.argv)
