#! /bin/bash

file_out = output/test_save_state_output

echo "this is stage 1" >> $file_out
for((i=0;i<100;i++)); do
	echo $i >> $file_out
done
echo "save_state()"
while read py_input do
	if($py_input = "continue") then
		echo "continuing" >> $file_out 
done

echo "save_state()"

done